### ISSUE TITLE
Počty Pythonistů - dynamické jazyky

### ISSUE THREAD

**Issue by MarekSuchanek** [EnyMan/PyDevSurvey#1]
1. Počet "How many Pythonist use dynamically typed languages?" je moc velký - když už víme, že pracujeme s Pythonisty, tak nepočítáme znovu Python - viz zadání.
2. V další odpovědi - jak statické, tak i dynamické je nesmysl, aby byl více než je některá z předchozích odpovědí - má se jednat o průnik.

**Comment by EnyMan** [comment]
opraveno

**Comment by MarekSuchanek** [comment]
OK 👍
