### ISSUE TITLE
Graf(y)

### ISSUE THREAD

**Issue by MarekSuchanek** [EnyMan/PyDevSurvey#2]
1. První graf je prázdný?
2. "ukáže procento Pythonistů" (viz zadání)
3. Ideálně 1 graf - "vykreslete graf" (ne grafy, viz zadání)
4. Chybí řada "Pouze Python"

**Comment by EnyMan** [comment]
@MarekSuchanek Jestli to chápu správně tak mám udělat jeden graf ve kterém bude pro každý jazyk, krom pytohnu, kolik procent pythonistu, kteří tento jazyk používájí pracují na pouze jednom, více nebo mhona projektech? Nějak nechápu tu řadu "Pouze Python", napadá mě jen zobrazit lidi co používají jen Python a nic jiného?

**Comment by MarekSuchanek** [comment]
Ano, je to tak... "Pouze Python" jsou pythonisti, co používají jen Python a zase ty 3 možnosti (pouze 1, 1 hlavní + vedlejší, mnoha).

**Comment by MarekSuchanek** [comment]
U těch popisků není úplně jasné co je "several" a co "multiple" - držel bych se spíš popisu podle zadání...

**Comment by EnyMan** [comment]
@MarekSuchanek Opraveno, přídano "Only Python" a upravil jsem legendu

**Comment by MarekSuchanek** [comment]
OK 👍
